# SPDX-FileCopyrightText: lowRISC contributors
# SPDX-License-Identifier: Apache-2.0
# SPDX-FileContributor: Hugo McNally

version = 1
SPDX-PackageName = "FuseSoC Examples"
SPDX-PackageSupplier = "lowRISC"
SPDX-PackageDownloadLocation = "https://github.com/HU90m/fusesoc-examples"

[[annotations]]
path = ["*.lock", "**/*.svg", "**/*.md"]
precedence = "aggregate"
SPDX-FileCopyrightText = "lowRISC contributors"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "prims_lib/primgen_as_filter/*"
precedence = "aggregate"
SPDX-FileCopyrightText = "Olof Kindgren"
SPDX-License-Identifier = "Apache-2.0"
